
# Generated by Django 3.2.6 on 2021-08-21 10:02

from currency.currency_converter.currency_exchange_api import CurrencyExchangeAPI
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

def load_currencies_data(apps, schema_editor):
    CurrencyExchangeAPI().get_available_currencies()

class Migration(migrations.Migration):
    initial=False

    dependencies = [
        ('currency', '0001_initial')
    ]

    operations = [
        migrations.RunPython(load_currencies_data)
    ]