
# Generated by Django 3.2.6 on 2021-08-21 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from currency.currency_exchange.currency_exchange_api import CurrencyExchangeAPI

def load_data(apps, schema_editor):
    currencies = CurrencyExchangeAPI().get_available_currencies()
    Currency = apps.get_model('currency', 'Currency')
    Currency.objects.bulk_create(currencies)

class Migration(migrations.Migration):


    dependencies = [
        ('currency', '0001_initial')
    ]

    operations = [
        migrations.RunPython(load_data)
    ]